import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join, resolve} from 'node:path';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = fileURLToPath(new URL('../',import.meta.url));
const screenshotDir=resolve(root,process.env.BROWSER_SCREENSHOT_DIR || 'dist/browser-screenshots');
const server = spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,PORT:'4179'},stdio:'pipe'});
let browser;
try {
  let ready=false;
  for(let i=0;i<50;i++){
    try{if((await fetch('http://127.0.0.1:4179')).ok){ready=true;break;}}catch{}
    await new Promise(resolve=>setTimeout(resolve,100));
  }
  assert.ok(ready,'demo server must start');
  browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
  const page=await browser.newPage({viewport:{width:1440,height:1040}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:4179');
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('可以开始'));
  const original=await page.locator('#name').inputValue();
  await page.locator('#begin').click();
  await page.locator('#name').fill('临时工作区');
  await page.locator('#theme').selectOption('dark');
  assert.ok(await page.locator('#undo').isDisabled());
  await page.locator('#rollback').click();
  assert.equal(await page.locator('#name').inputValue(),original);
  assert.equal(await page.locator('#theme').inputValue(),'light');
  await page.locator('#begin').click();
  await page.locator('#name').fill('MoonUndo Studio');
  await page.locator('#theme').selectOption('dark');
  await page.locator('#commit').click();
  assert.equal(await page.locator('#depths').textContent(),'1 / 0');
  await page.locator('#save').click();
  await page.locator('#undo').click();
  assert.equal(await page.locator('#name').inputValue(),original);
  await page.locator('#redo').click();
  assert.equal(await page.locator('#dirty').textContent(),'与保存点一致');
  await page.locator('#name').fill('Changed');
  await page.locator('#restore').click();
  assert.equal(await page.locator('#name').inputValue(),'MoonUndo Studio');
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();
  const download=await downloadPromise;assert.equal(download.suggestedFilename(),'moonundo-settings.json');
  await page.locator('#name').fill('Before import');
  await page.locator('#import').setInputFiles(await download.path());
  await page.waitForFunction(()=>document.querySelector('#name').value==='MoonUndo Studio');
  await page.locator('#import').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('导入失败'));
  assert.equal(await page.locator('#name').inputValue(),'MoonUndo Studio');
  // A localStorage failure must not turn unsaved changes into a clean revision.
  await page.locator('#name').fill('Storage failure must stay dirty');
  await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new DOMException('Quota exceeded','QuotaExceededError');};});
  await page.locator('#save').click();
  assert.equal(await page.locator('#dirty').textContent(),'有未保存的修改');
  assert.match(await page.locator('#message').textContent(),/保存失败/);
  await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;});
  await page.locator('#restore').click();
  // Artificially defer reading a selected file, then edit before it completes.
  const archive=await page.evaluate(()=>localStorage.getItem('moonundo:settings'));
  await page.evaluate(text=>{window.originalFileText=File.prototype.text;File.prototype.text=function(){return new Promise(resolve=>{window.finishImport=()=>resolve(text);});};},archive);
  await page.locator('#import').setInputFiles({name:'deferred.json',mimeType:'application/json',buffer:Buffer.from(archive)});
  await page.waitForFunction(()=>typeof window.finishImport==='function');
  await page.locator('#name').fill('Keep the newer edit');
  await page.evaluate(()=>{window.finishImport();File.prototype.text=window.originalFileText;});
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('读取文件期间'));
  assert.equal(await page.locator('#name').inputValue(),'Keep the newer edit');
  await page.locator('#restore').click();
  await page.locator('#begin').click();
  await page.evaluate(()=>{const input=document.querySelector('#name');for(let i=0;i<2200;i++){input.value='Long preview '+i;input.dispatchEvent(new Event('input',{bubbles:true}));}});
  await page.locator('#rollback').click();
  assert.equal(await page.locator('#name').inputValue(),'MoonUndo Studio');
  await page.locator('#save').click();
  await mkdir(screenshotDir,{recursive:true});
  await page.screenshot({path:join(screenshotDir,'settings.png'),fullPage:true});

  await page.locator('[data-tab="tasks"]').click();
  await page.locator('#task-title').fill('验收演示 <script>');
  await page.locator('#task-form button').click();
  assert.equal(await page.locator('#task-list li').count(),3);
  await page.locator('#task-list li').last().locator('button').click();
  assert.equal(await page.locator('#task-list li').count(),2);
  await page.locator('#undo').click();
  assert.equal(await page.locator('#task-list li').count(),3);
  await page.locator('#complete-all').click();
  assert.equal(await page.locator('#task-list .done').count(),3);
  await page.locator('#undo').click();
  assert.equal(await page.locator('#task-list .done').count(),0);
  await page.screenshot({path:join(screenshotDir,'tasks.png'),fullPage:true});

  await page.locator('[data-tab="canvas"]').click();
  const shape=page.locator('[data-id="1"]');
  const before=await shape.getAttribute('style');
  const bounds=await shape.boundingBox();
  await page.mouse.move(bounds.x+20,bounds.y+20);await page.mouse.down();
  await page.mouse.move(bounds.x+110,bounds.y+80,{steps:12});await page.mouse.up();
  assert.notEqual(await shape.getAttribute('style'),before);
  assert.equal(await page.locator('#depths').textContent(),'1 / 0');
  await page.locator('#undo').click();
  assert.equal(await shape.getAttribute('style'),before);
  await page.locator('#redo').click();
  await page.locator('#color-shape').click();
  await page.screenshot({path:join(screenshotDir,'canvas.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile page must not overflow horizontally');
  await page.screenshot({path:join(screenshotDir,'mobile.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Browser acceptance passed: settings transactions, saved session, export/import, tasks, drag grouping, mobile layout, no runtime errors.');
} finally { await browser?.close(); server.kill(); }

